name: kpss_app
description: "KPSS Öğrenme Uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1  
  # Ekledigimiz kütüphaneler
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Görselleri buraya ekliyoruz
  assets:
    - assets/images/
  fonts:
    - family: Omnes
      fonts:
        - asset: assets/fonts/Omnes Bold.ttf
          weight: 700  # Bold olduğu için 700 dedik

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # Bunu eklemek yeni androidlerde hata almanı önler